
CREATE TABLE tech_stack(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(100) NOT NULL ,
    logo_url VARCHAR(500) NOT NULL ,
    category VARCHAR(50) ,
    created_by_id BIGINT NOT NULL ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tech_stack_created_by FOREIGN KEY (created_by_id) REFERENCES waft_user(id) ON DELETE RESTRICT
)