
CREATE TABLE contact_inquiry(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL ,
    email VARCHAR(150) NOT NULL ,
    services JSON,
    message TEXT,
    document_url VARCHAR(500) ,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

)