
#Server
server.port=8080

#H2
spring.datasource.url=jdbc:h2:mem:wafttech_dev
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin-user
spring.datasource.password=admin@123

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA

#auto-detected by default
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Fly-base
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



